version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - pg_data:/data/postgres
       - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin4}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_data:/root/.pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80
    networks:
      - backend
    restart: unless-stopped

  web:
    build: .
    environment:
      ADDRESS: 0.0.0.0:8000
      POSTGRES_DB: ocp_presentation_api
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      CHUNK_SIZE: 10
    depends_on:
      - postgres
    ports:
      - ${PORT:-8000}:8000
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
  pgadmin_data:
