// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/ocp-presentation-api/ocp-presentation-api.proto

package ocp_presentation_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on CreatePresentationV1Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreatePresentationV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPresentation() == nil {
		return CreatePresentationV1RequestValidationError{
			field:  "Presentation",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetPresentation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreatePresentationV1RequestValidationError{
				field:  "Presentation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreatePresentationV1RequestValidationError is the validation error returned
// by CreatePresentationV1Request.Validate if the designated constraints
// aren't met.
type CreatePresentationV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePresentationV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePresentationV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePresentationV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePresentationV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePresentationV1RequestValidationError) ErrorName() string {
	return "CreatePresentationV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePresentationV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePresentationV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePresentationV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePresentationV1RequestValidationError{}

// Validate checks the field values on CreatePresentationV1Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreatePresentationV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PresentationId

	return nil
}

// CreatePresentationV1ResponseValidationError is the validation error returned
// by CreatePresentationV1Response.Validate if the designated constraints
// aren't met.
type CreatePresentationV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePresentationV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePresentationV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePresentationV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePresentationV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePresentationV1ResponseValidationError) ErrorName() string {
	return "CreatePresentationV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePresentationV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePresentationV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePresentationV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePresentationV1ResponseValidationError{}

// Validate checks the field values on MultiCreatePresentationsV1Request with
// the rules defined in the proto definition for this message. If any rules
// are violated, an error is returned.
func (m *MultiCreatePresentationsV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if l := len(m.GetPresentations()); l < 1 || l > 1024 {
		return MultiCreatePresentationsV1RequestValidationError{
			field:  "Presentations",
			reason: "value must contain between 1 and 1024 items, inclusive",
		}
	}

	for idx, item := range m.GetPresentations() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MultiCreatePresentationsV1RequestValidationError{
					field:  fmt.Sprintf("Presentations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// MultiCreatePresentationsV1RequestValidationError is the validation error
// returned by MultiCreatePresentationsV1Request.Validate if the designated
// constraints aren't met.
type MultiCreatePresentationsV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MultiCreatePresentationsV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MultiCreatePresentationsV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MultiCreatePresentationsV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MultiCreatePresentationsV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MultiCreatePresentationsV1RequestValidationError) ErrorName() string {
	return "MultiCreatePresentationsV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e MultiCreatePresentationsV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMultiCreatePresentationsV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MultiCreatePresentationsV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MultiCreatePresentationsV1RequestValidationError{}

// Validate checks the field values on MultiCreatePresentationsV1Response with
// the rules defined in the proto definition for this message. If any rules
// are violated, an error is returned.
func (m *MultiCreatePresentationsV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for NumberOfCreatedPresentations

	return nil
}

// MultiCreatePresentationsV1ResponseValidationError is the validation error
// returned by MultiCreatePresentationsV1Response.Validate if the designated
// constraints aren't met.
type MultiCreatePresentationsV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MultiCreatePresentationsV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MultiCreatePresentationsV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MultiCreatePresentationsV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MultiCreatePresentationsV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MultiCreatePresentationsV1ResponseValidationError) ErrorName() string {
	return "MultiCreatePresentationsV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MultiCreatePresentationsV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMultiCreatePresentationsV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MultiCreatePresentationsV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MultiCreatePresentationsV1ResponseValidationError{}

// Validate checks the field values on UpdatePresentationV1Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdatePresentationV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPresentation() == nil {
		return UpdatePresentationV1RequestValidationError{
			field:  "Presentation",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetPresentation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdatePresentationV1RequestValidationError{
				field:  "Presentation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdatePresentationV1RequestValidationError is the validation error returned
// by UpdatePresentationV1Request.Validate if the designated constraints
// aren't met.
type UpdatePresentationV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePresentationV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePresentationV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePresentationV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePresentationV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePresentationV1RequestValidationError) ErrorName() string {
	return "UpdatePresentationV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatePresentationV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePresentationV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePresentationV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePresentationV1RequestValidationError{}

// Validate checks the field values on UpdatePresentationV1Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdatePresentationV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Found

	return nil
}

// UpdatePresentationV1ResponseValidationError is the validation error returned
// by UpdatePresentationV1Response.Validate if the designated constraints
// aren't met.
type UpdatePresentationV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePresentationV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePresentationV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePresentationV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePresentationV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePresentationV1ResponseValidationError) ErrorName() string {
	return "UpdatePresentationV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatePresentationV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePresentationV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePresentationV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePresentationV1ResponseValidationError{}

// Validate checks the field values on DescribePresentationV1Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribePresentationV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPresentationId() < 1 {
		return DescribePresentationV1RequestValidationError{
			field:  "PresentationId",
			reason: "value must be greater than or equal to 1",
		}
	}

	return nil
}

// DescribePresentationV1RequestValidationError is the validation error
// returned by DescribePresentationV1Request.Validate if the designated
// constraints aren't met.
type DescribePresentationV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribePresentationV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribePresentationV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribePresentationV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribePresentationV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribePresentationV1RequestValidationError) ErrorName() string {
	return "DescribePresentationV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribePresentationV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribePresentationV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribePresentationV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribePresentationV1RequestValidationError{}

// Validate checks the field values on DescribePresentationV1Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribePresentationV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetPresentation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribePresentationV1ResponseValidationError{
				field:  "Presentation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribePresentationV1ResponseValidationError is the validation error
// returned by DescribePresentationV1Response.Validate if the designated
// constraints aren't met.
type DescribePresentationV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribePresentationV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribePresentationV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribePresentationV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribePresentationV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribePresentationV1ResponseValidationError) ErrorName() string {
	return "DescribePresentationV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribePresentationV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribePresentationV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribePresentationV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribePresentationV1ResponseValidationError{}

// Validate checks the field values on ListPresentationsV1Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListPresentationsV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if val := m.GetLimit(); val < 1 || val > 1024 {
		return ListPresentationsV1RequestValidationError{
			field:  "Limit",
			reason: "value must be inside range [1, 1024]",
		}
	}

	// no validation rules for Offset

	return nil
}

// ListPresentationsV1RequestValidationError is the validation error returned
// by ListPresentationsV1Request.Validate if the designated constraints aren't met.
type ListPresentationsV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPresentationsV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPresentationsV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPresentationsV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPresentationsV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPresentationsV1RequestValidationError) ErrorName() string {
	return "ListPresentationsV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPresentationsV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPresentationsV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPresentationsV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPresentationsV1RequestValidationError{}

// Validate checks the field values on ListPresentationsV1Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListPresentationsV1Response) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetPresentations() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPresentationsV1ResponseValidationError{
					field:  fmt.Sprintf("Presentations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListPresentationsV1ResponseValidationError is the validation error returned
// by ListPresentationsV1Response.Validate if the designated constraints
// aren't met.
type ListPresentationsV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPresentationsV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPresentationsV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPresentationsV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPresentationsV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPresentationsV1ResponseValidationError) ErrorName() string {
	return "ListPresentationsV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPresentationsV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPresentationsV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPresentationsV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPresentationsV1ResponseValidationError{}

// Validate checks the field values on RemovePresentationV1Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemovePresentationV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPresentationId() < 1 {
		return RemovePresentationV1RequestValidationError{
			field:  "PresentationId",
			reason: "value must be greater than or equal to 1",
		}
	}

	return nil
}

// RemovePresentationV1RequestValidationError is the validation error returned
// by RemovePresentationV1Request.Validate if the designated constraints
// aren't met.
type RemovePresentationV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemovePresentationV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemovePresentationV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemovePresentationV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemovePresentationV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemovePresentationV1RequestValidationError) ErrorName() string {
	return "RemovePresentationV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemovePresentationV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemovePresentationV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemovePresentationV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemovePresentationV1RequestValidationError{}

// Validate checks the field values on RemovePresentationV1Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemovePresentationV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Found

	return nil
}

// RemovePresentationV1ResponseValidationError is the validation error returned
// by RemovePresentationV1Response.Validate if the designated constraints
// aren't met.
type RemovePresentationV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemovePresentationV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemovePresentationV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemovePresentationV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemovePresentationV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemovePresentationV1ResponseValidationError) ErrorName() string {
	return "RemovePresentationV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemovePresentationV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemovePresentationV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemovePresentationV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemovePresentationV1ResponseValidationError{}

// Validate checks the field values on NewPresentation with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *NewPresentation) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetUserId() < 1 {
		return NewPresentationValidationError{
			field:  "UserId",
			reason: "value must be greater than or equal to 1",
		}
	}

	if m.GetLessonId() < 1 {
		return NewPresentationValidationError{
			field:  "LessonId",
			reason: "value must be greater than or equal to 1",
		}
	}

	if utf8.RuneCountInString(m.GetName()) > 256 {
		return NewPresentationValidationError{
			field:  "Name",
			reason: "value length must be at most 256 runes",
		}
	}

	if utf8.RuneCountInString(m.GetDescription()) > 1024 {
		return NewPresentationValidationError{
			field:  "Description",
			reason: "value length must be at most 1024 runes",
		}
	}

	return nil
}

// NewPresentationValidationError is the validation error returned by
// NewPresentation.Validate if the designated constraints aren't met.
type NewPresentationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewPresentationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewPresentationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewPresentationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewPresentationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewPresentationValidationError) ErrorName() string { return "NewPresentationValidationError" }

// Error satisfies the builtin error interface
func (e NewPresentationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewPresentation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewPresentationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewPresentationValidationError{}

// Validate checks the field values on Presentation with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *Presentation) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetId() < 1 {
		return PresentationValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 1",
		}
	}

	if m.GetUserId() < 1 {
		return PresentationValidationError{
			field:  "UserId",
			reason: "value must be greater than or equal to 1",
		}
	}

	if m.GetLessonId() < 1 {
		return PresentationValidationError{
			field:  "LessonId",
			reason: "value must be greater than or equal to 1",
		}
	}

	if utf8.RuneCountInString(m.GetName()) > 256 {
		return PresentationValidationError{
			field:  "Name",
			reason: "value length must be at most 256 runes",
		}
	}

	if utf8.RuneCountInString(m.GetDescription()) > 1024 {
		return PresentationValidationError{
			field:  "Description",
			reason: "value length must be at most 1024 runes",
		}
	}

	return nil
}

// PresentationValidationError is the validation error returned by
// Presentation.Validate if the designated constraints aren't met.
type PresentationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PresentationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PresentationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PresentationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PresentationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PresentationValidationError) ErrorName() string { return "PresentationValidationError" }

// Error satisfies the builtin error interface
func (e PresentationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPresentation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PresentationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PresentationValidationError{}
